package net.blay09.balybot;

import net.blay09.balybot.impl.base.BaseImplementation;
import org.intellij.lang.annotations.Language;

import java.sql.*;

public class Database {

	public enum Type {
		SQLITE,
		MYSQL
	}

    private static Connection connection;

	private static PreparedStatement setChannelConfig;
	private static PreparedStatement addNewServer;
	private static PreparedStatement addNewChannel;
	private static PreparedStatement setChannelActive;
	private static PreparedStatement activateModule;
	private static PreparedStatement deactivateModule;

    public static void connect() throws ClassNotFoundException, SQLException {
		if(BaseImplementation.getDatabaseType() == Type.SQLITE) {
			Class.forName("org.sqlite.JDBC");
			connection = DriverManager.getConnection("jdbc:sqlite:" + BaseImplementation.getDatabaseName());
		} else if(BaseImplementation.getDatabaseType() == Type.MYSQL) {
			Class.forName("com.mysql.cj.jdbc.Driver");
			connection = DriverManager.getConnection("jdbc:mysql://" + BaseImplementation.getDatabaseHost() + "/" + BaseImplementation.getDatabaseName() + "?user=" + BaseImplementation.getDatabaseUser() + "&password=" + BaseImplementation.getDatabasePassword() + "&useSSL=false&serverTimezone=UTC");
		} else {
			throw new RuntimeException("Unknown database type specified, aborting");
		}

		createTable("servers", true,
				"`host` VARCHAR(256) NOT NULL",
				"`implementation` VARCHAR(32)");
		createTable("channels", true,
				"`server_fk` INTEGER",
				"`name` VARCHAR(64) NOT NULL",
				"`is_active` BOOLEAN DEFAULT TRUE");
		createTable("active_modules", false,
				"`channel_fk` INTEGER",
				"`module_id` VARCHAR(64)",
				"PRIMARY KEY(`channel_fk`, `module_id`)");
		createTable("channel_config", false,
				"`channel_fk` INTEGER",
				"`name` VARCHAR(64)",
				"`value` TEXT NOT NULL",
				"PRIMARY KEY(`channel_fk`, `name`)");

		addNewServer = connection.prepareStatement("INSERT INTO `servers` (`host`, `implementation`) VALUES(?,?)", Statement.RETURN_GENERATED_KEYS);
		addNewChannel = connection.prepareStatement("INSERT INTO `channels` (`name`, `server_fk`) VALUES (?, ?)", Statement.RETURN_GENERATED_KEYS);
		setChannelActive = connection.prepareStatement("UPDATE `channels` SET `is_active` = ? WHERE `id` = ?");
		setChannelConfig = connection.prepareStatement("REPLACE INTO `channel_config` (`channel_fk`, `name`, `value`) VALUES (?, ?, ?)");
		activateModule = connection.prepareStatement("REPLACE INTO `active_modules` (`channel_fk`, `module_id`) VALUES(?, ?)");
		deactivateModule = connection.prepareStatement("DELETE FROM `active_modules` WHERE `channel_fk` = ? AND `module_id` = ?");
    }

	public static void createTable(String tableName, boolean withId, String... fields) throws SQLException {
		StringBuilder sb = new StringBuilder();
		sb.append("CREATE TABLE IF NOT EXISTS ");
		sb.append('`').append(tableName).append('`');
		sb.append(" (");
		if(withId) {
			sb.append("id INTEGER PRIMARY KEY");
			if(BaseImplementation.getDatabaseType() == Type.MYSQL) {
				sb.append(" AUTO_INCREMENT");
			}
			sb.append(", ");
		}
		for(int i = 0; i < fields.length; i++) {
			if(i > 0) {
				sb.append(", ");
			}
			sb.append(fields[i]);
		}
		sb.append(")");
		execute(sb.toString());
	}

	public static Statement createStatement() throws SQLException {
        return connection.createStatement();
    }

	public static PreparedStatement prepareStatement(String sql) throws SQLException {
		return connection.prepareStatement(sql);
	}

    public static PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }

    public static void execute(@Language("SQL") String sql) throws SQLException {
        Statement stmt = connection.createStatement();
        stmt.execute(sql);
        stmt.close();
    }

	public static int addNewServer(String serverHost, String implementation) throws SQLException {
		addNewServer.setString(1, serverHost);
		addNewServer.setString(2, implementation);
		addNewServer.execute();
		ResultSet rs = addNewServer.getGeneratedKeys();
		if(rs.next()) {
			return rs.getInt(1);
		}
		return 0;
	}

	public static int addNewChannel(String channelName, int serverFK) throws SQLException {
		addNewChannel.setString(1, channelName);
		addNewChannel.setInt(2, serverFK);
		addNewChannel.execute();
		ResultSet rs = addNewChannel.getGeneratedKeys();
		if(rs.next()) {
			return rs.getInt(1);
		}
		return 0;
	}

	public static void setChannelActive(int channelId, boolean active) throws SQLException {
		setChannelActive.setInt(1, channelId);
		setChannelActive.setBoolean(2, active);
		setChannelActive.execute();
	}

	public static void setChannelConfig(int channelId, String option, String value) throws SQLException {
		setChannelConfig.setInt(1, channelId);
		setChannelConfig.setString(2, option);
		setChannelConfig.setString(3, value);
		setChannelConfig.execute();
	}

	public static void activateModule(int channelId, String moduleId) throws SQLException {
		activateModule.setInt(1, channelId);
		activateModule.setString(2, moduleId);
		activateModule.execute();
	}

	public static void deactivateModule(int channelId, String moduleId) throws SQLException {
		deactivateModule.setInt(1, channelId);
		deactivateModule.setString(2, moduleId);
		deactivateModule.execute();
	}
}
